export const types = {
    ADD_TO_CART: 'ADD_TO_CART',
    ADD_CATEGORY: 'ADD_CATEGORY',
    ADD_TO_DATA_CONTAINER: 'ADD_TO_DATA_CONTAINER',
    SORT_BY_DESC: 'SORT_BY_DESC',
    SORT_BY_ASC: 'SORT_BY_ASC',
    SORT_BY_ASC_RATE: 'SORT_BY_ASC_RATE',
    SORT_BY_DESC_RATE: 'SORT_BY_DESC_RATE',
    CLEAN_DATA: 'CLEAN_DATA',
    CLEAN_LIST: 'CLEAN_LIST',
    REMOVE_ONE: 'REMOVE_ONE',
    REMOVE_ALL: 'REMOVE_ALL',
    CHANGE_LOADING_MSG: 'CHANGE_LOADING_MSG',
    SORT_BY_ZA: 'SORT_BY_ZA',
    SORT_BY_AZ: 'SORT_BY_AZ'
}